#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Beacons.Resource", IsApplication=true)]

namespace Beacons
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int image0 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int image1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int image2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int image3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Xamarin_Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int BeaconsView = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int demoImageView = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int statusLabel = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int statusLabel2 = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Xamarin_Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000a
			public const int app_label = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int app_name = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int changeImage = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int error_no_bluetooth_enabled = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int error_no_bluetooth_le = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int error_no_location_permission = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int monkey_notification = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int requesting_location_access = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int requesting_location_access_cancel = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int requesting_location_access_ok = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int requesting_location_access_rationale = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int requesting_location_permission = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int requesting_location_permission_rationale = 2131034120;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Transparent = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
