#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Beacons.Resource", IsApplication=true)]

namespace Beacons
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bowls = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Burritos = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Ensalada = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Freshii_icon_original = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Frozen_yogurt = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int greenbackgroud = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int image0 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Jugos = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Salads1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Salads2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Smoothies = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Sopas = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Teriyaki_twist = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Xamarin_Icon = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int BeaconsView = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int ImageHome = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int WelcomeButton = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int demoImageView = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int scrollView = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int statusLabel = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int statusLabel2 = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Menu1ScrollView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Menu2ScrollView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Menu3ScrollView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Welcome = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000a
			public const int app_label = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int app_name = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int changeImage = 2130968588;
			
			// aapt resource value: 0x7f040000
			public const int error_no_bluetooth_enabled = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int error_no_bluetooth_le = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int error_no_location_permission = 2130968578;
			
			// aapt resource value: 0x7f04000b
			public const int monkey_notification = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int requesting_location_access = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int requesting_location_access_cancel = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int requesting_location_access_ok = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int requesting_location_access_rationale = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int requesting_location_permission = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int requesting_location_permission_rationale = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Transparent = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
